### ISSUE TITLE
Twitterアカウント認証処理について

### ISSUE THREAD

**Issue by ghost** [orekyuu/JavaBeamStudioOld#12]
Twitterアカウントを新規登録する際、認証情報の反映に再起動が必要なのは、個人的には不便だなぁと。
あと、PINコード入力画面がモーダルではないため、設定画面などの後ろに隠れてしまい、不便だと思いました。

**Comment by orekyuu** [comment]
修正　マージ待ち
https://github.com/orekyuu/JavaBeamStudio/pull/16

**Comment by orekyuu** [comment]
対応完了
